name: openai-for-java

on:
  push:
    branches: [main]

env:
  OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
  OPEN_AI_ORGANIZATION: ${{ secrets.OPEN_AI_ORGANIZATION }}
  JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
  JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: openai-for-java

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew check -Dopen.ai.api.key=${{ env.OPEN_AI_API_KEY }} -Dopen.ai.organization=${{ env.OPEN_AI_ORGANIZATION }} -Djira.username=${{ env.JIRA_USERNAME }} -Djira.password=${{ env.JIRA_PASSWORD }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: true
      - name: Display test status badge
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
          output: file
          file: build/reports/jacoco/test/jacocoTestReport.xml
          ignore:
            - "**/examples/**"
            - "**/Example**"
        continue-on-error: true